2025-08-19T14:12:10.354Z [ERROR]: Traceback (most recent call last):
2025-08-19T14:12:10.357Z [ERROR]: File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
    return method_to_call(*args)
  File "C:\Users\hari2\AppData\Local\Temp\temp-python-code-1755612729627-d811756a36685.py", line 5, in main
    data = json.loads(output)
  File "C:\Users\hari2\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
                    f'not {s.__class__.__name__}')
TypeError: the JSON object must be str, bytes or bytearray, not dict
2025-08-19T14:12:10.360Z [ERROR]: Error running Python script: TypeError: the JSON object must be str, bytes or bytearray, not dict
Stack Trace: Error: TypeError: the JSON object must be str, bytes or bytearray, not dict
    at PythonShell.parseError (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at Socket.<anonymous> (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:164:17)
    at Socket.emit (node:events:536:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
    --Python Traceback: --
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
    File "C:\Users\hari2\AppData\Local\Temp\temp-python-code-1755612729627-d811756a36685.py", line 5, in main
      data = json.loads(output)
    File "C:\Users\hari2\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 339, in loads
      raise TypeError(f'the JSON object must be str, bytes or bytearray, '
                      f'not {s.__class__.__name__}')
2025-08-19T14:12:10.361Z [ERROR]: Error removing C:\Users\hari2\AppData\Local\Temp\promptfoo-python-output-json-1755612729628-23dbeea5293b3.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\hari2\AppData\Local\Temp\promptfoo-python-output-json-1755612729628-23dbeea5293b3.json'
2025-08-19T14:12:10.361Z [ERROR]: Error executing Python code: Error: Error running Python script: TypeError: the JSON object must be str, bytes or bytearray, not dict
Stack Trace: Error: TypeError: the JSON object must be str, bytes or bytearray, not dict
    at PythonShell.parseError (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at Socket.<anonymous> (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:164:17)
    at Socket.emit (node:events:536:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
    --Python Traceback: --
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
    File "C:\Users\hari2\AppData\Local\Temp\temp-python-code-1755612729627-d811756a36685.py", line 5, in main
      data = json.loads(output)
    File "C:\Users\hari2\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 339, in loads
      raise TypeError(f'the JSON object must be str, bytes or bytearray, '
                      f'not {s.__class__.__name__}')
2025-08-19T15:16:02.698Z [ERROR]: Traceback (most recent call last):
  File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
    return method_to_call(*args)
  File "C:\Users\hari2\AppData\Local\Temp\temp-python-code-1755616562213-4d556e2099b59.py", line 4, in main
    if output["total_sales"] == 1140:
       ~~~~~~^^^^^^^^^^^^^^^
KeyError: 'total_sales'
2025-08-19T15:16:02.723Z [ERROR]: Traceback (most recent call last):
  File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
    return method_to_call(*args)
  File "C:\Users\hari2\AppData\Local\Temp\temp-python-code-1755616562226-bcaafb93b9cdc.py", line 4, in main
    val = float(output["day_sales_correlation"])
                ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'day_sales_correlation'
2025-08-19T15:16:02.726Z [ERROR]: Traceback (most recent call last):
  File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
    return method_to_call(*args)
  File "C:\Users\hari2\AppData\Local\Temp\temp-python-code-1755616562224-35bb1c116b83c.py", line 4, in main
    if output["top_region"].lower() == "west":
       ~~~~~~^^^^^^^^^^^^^^
KeyError: 'top_region'
2025-08-19T15:16:02.735Z [ERROR]: Error running Python script: KeyError: 'total_sales'
Stack Trace: Error: KeyError: 'total_sales'
    at PythonShell.parseError (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
    --Python Traceback: --
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
    File "C:\Users\hari2\AppData\Local\Temp\temp-python-code-1755616562213-4d556e2099b59.py", line 4, in main
      if output["total_sales"] == 1140:
         ~~~~~~^^^^^^^^^^^^^^^
2025-08-19T15:16:02.737Z [ERROR]: Error removing C:\Users\hari2\AppData\Local\Temp\promptfoo-python-output-json-1755616562214-f6d1fae0b7dc3.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\hari2\AppData\Local\Temp\promptfoo-python-output-json-1755616562214-f6d1fae0b7dc3.json'
2025-08-19T15:16:02.738Z [ERROR]: Error executing Python code: Error: Error running Python script: KeyError: 'total_sales'
Stack Trace: Error: KeyError: 'total_sales'
    at PythonShell.parseError (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
    --Python Traceback: --
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
    File "C:\Users\hari2\AppData\Local\Temp\temp-python-code-1755616562213-4d556e2099b59.py", line 4, in main
      if output["total_sales"] == 1140:
         ~~~~~~^^^^^^^^^^^^^^^
2025-08-19T15:16:02.764Z [ERROR]: Error running Python script: KeyError: 'day_sales_correlation'
Stack Trace: Error: KeyError: 'day_sales_correlation'
    at PythonShell.parseError (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
    --Python Traceback: --
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
    File "C:\Users\hari2\AppData\Local\Temp\temp-python-code-1755616562226-bcaafb93b9cdc.py", line 4, in main
      val = float(output["day_sales_correlation"])
                  ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-19T15:16:02.766Z [ERROR]: Error removing C:\Users\hari2\AppData\Local\Temp\promptfoo-python-output-json-1755616562312-1f70caa1bd04c.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\hari2\AppData\Local\Temp\promptfoo-python-output-json-1755616562312-1f70caa1bd04c.json'
2025-08-19T15:16:02.766Z [ERROR]: Error executing Python code: Error: Error running Python script: KeyError: 'day_sales_correlation'
Stack Trace: Error: KeyError: 'day_sales_correlation'
    at PythonShell.parseError (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
    --Python Traceback: --
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
    File "C:\Users\hari2\AppData\Local\Temp\temp-python-code-1755616562226-bcaafb93b9cdc.py", line 4, in main
      val = float(output["day_sales_correlation"])
                  ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-19T15:16:02.784Z [ERROR]: Error running Python script: KeyError: 'top_region'
Stack Trace: Error: KeyError: 'top_region'
    at PythonShell.parseError (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
    --Python Traceback: --
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
    File "C:\Users\hari2\AppData\Local\Temp\temp-python-code-1755616562224-35bb1c116b83c.py", line 4, in main
      if output["top_region"].lower() == "west":
         ~~~~~~^^^^^^^^^^^^^^
2025-08-19T15:16:02.785Z [ERROR]: Error removing C:\Users\hari2\AppData\Local\Temp\promptfoo-python-output-json-1755616562225-13bfbe819a24f.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\hari2\AppData\Local\Temp\promptfoo-python-output-json-1755616562225-13bfbe819a24f.json'
2025-08-19T15:16:02.786Z [ERROR]: Error executing Python code: Error: Error running Python script: KeyError: 'top_region'
Stack Trace: Error: KeyError: 'top_region'
    at PythonShell.parseError (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
    --Python Traceback: --
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
    File "C:\Users\hari2\AppData\Local\Temp\temp-python-code-1755616562224-35bb1c116b83c.py", line 4, in main
      if output["top_region"].lower() == "west":
         ~~~~~~^^^^^^^^^^^^^^
2025-08-19T15:16:02.957Z [ERROR]: Traceback (most recent call last):
2025-08-19T15:16:02.958Z [ERROR]: File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
    return method_to_call(*args)
  File "C:\Users\hari2\AppData\Local\Temp\temp-python-code-1755616562739-e9b13c0b8a285.py", line 4, in main
    if output["median_sales"] == 140:
       ~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'median_sales'
2025-08-19T15:16:02.977Z [ERROR]: Traceback (most recent call last):
2025-08-19T15:16:02.978Z [ERROR]: File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
    return method_to_call(*args)
  File "C:\Users\hari2\AppData\Local\Temp\temp-python-code-1755616562768-b178c2f434be2.py", line 4, in main
    if output["total_sales_tax"] == 114:
       ~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'total_sales_tax'
2025-08-19T15:16:02.985Z [ERROR]: Error running Python script: KeyError: 'median_sales'
Stack Trace: Error: KeyError: 'median_sales'
    at PythonShell.parseError (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
    --Python Traceback: --
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
    File "C:\Users\hari2\AppData\Local\Temp\temp-python-code-1755616562739-e9b13c0b8a285.py", line 4, in main
      if output["median_sales"] == 140:
         ~~~~~~^^^^^^^^^^^^^^^^
2025-08-19T15:16:02.986Z [ERROR]: Error removing C:\Users\hari2\AppData\Local\Temp\promptfoo-python-output-json-1755616562741-31e93845a79be.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\hari2\AppData\Local\Temp\promptfoo-python-output-json-1755616562741-31e93845a79be.json'
2025-08-19T15:16:02.986Z [ERROR]: Error executing Python code: Error: Error running Python script: KeyError: 'median_sales'
Stack Trace: Error: KeyError: 'median_sales'
    at PythonShell.parseError (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
    --Python Traceback: --
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
    File "C:\Users\hari2\AppData\Local\Temp\temp-python-code-1755616562739-e9b13c0b8a285.py", line 4, in main
      if output["median_sales"] == 140:
         ~~~~~~^^^^^^^^^^^^^^^^
2025-08-19T15:16:03.001Z [ERROR]: Error running Python script: KeyError: 'total_sales_tax'
Stack Trace: Error: KeyError: 'total_sales_tax'
    at PythonShell.parseError (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
    --Python Traceback: --
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
    File "C:\Users\hari2\AppData\Local\Temp\temp-python-code-1755616562768-b178c2f434be2.py", line 4, in main
      if output["total_sales_tax"] == 114:
         ~~~~~~^^^^^^^^^^^^^^^^^^^
2025-08-19T15:16:03.002Z [ERROR]: Error removing C:\Users\hari2\AppData\Local\Temp\promptfoo-python-output-json-1755616562769-66699381da0e3.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\hari2\AppData\Local\Temp\promptfoo-python-output-json-1755616562769-66699381da0e3.json'
2025-08-19T15:16:03.003Z [ERROR]: Error executing Python code: Error: Error running Python script: KeyError: 'total_sales_tax'
Stack Trace: Error: KeyError: 'total_sales_tax'
    at PythonShell.parseError (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
    --Python Traceback: --
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\hari2\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
    File "C:\Users\hari2\AppData\Local\Temp\temp-python-code-1755616562768-b178c2f434be2.py", line 4, in main
      if output["total_sales_tax"] == 114:
         ~~~~~~^^^^^^^^^^^^^^^^^^^
2025-08-19T15:21:06.156Z [ERROR]: API call error: Error: Request failed after 4 retries: undefined
2025-08-19T15:21:10.558Z [ERROR]: API call error: Error: Request failed after 4 retries: undefined
